version: '2.3'

services:
  rest-api-app:
    image: maxca789/apachephp72composer
    container_name: rest-api-lumen
    ports:
      - "8021:80"
    volumes:
      - .:/var/www/html/
     # - ./docker/vhost/:/etc/apache2/sites-available/
    networks:
      - rest-api
      - mysql_mysqlnetwork
    environment:
      - CONTAINER_TIMEZONE=Asia/Bangkok
      - VIRTUAL_HOST=local-vhost.dev

networks:
  rest-api:
    driver: bridge
  mysql_mysqlnetwork:
    external: true
